In [1]:
#haystack
import numpy as np

array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Horizontally stack the arrays
result = np.hstack((array1, array2))

print(result)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [2]:
import pandas as pd
import numpy as np

# Set a random seed for reproducibility
np.random.seed(42)

# Create a DataFrame with seven independent features
num_samples = 100  # Number of samples
independent_features = {
    f'feature_{i}': np.random.rand(num_samples) for i in range(1, 8)
}

# Add a dependent feature (binary, 0 or 1)
independent_features['dependent'] = np.random.choice([0, 1], size=num_samples)

# Create the DataFrame
df = pd.DataFrame(independent_features)

# Calculate the correlation matrix
correlation_matrix = df.corr()

# Display the DataFrame and the correlation matrix
print("DataFrame:")
print(df.head())
print("\nCorrelation Matrix:")
print(correlation_matrix)

DataFrame:
   feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0   0.374540   0.031429   0.642032   0.051682   0.103124   0.698162   
1   0.950714   0.636410   0.084140   0.531355   0.902553   0.536096   
2   0.731994   0.314356   0.161629   0.540635   0.505252   0.309528   
3   0.598658   0.508571   0.898554   0.637430   0.826457   0.813795   
4   0.156019   0.907566   0.606429   0.726091   0.320050   0.684731   

   feature_7  dependent  
0   0.168935          0  
1   0.278590          0  
2   0.177010          0  
3   0.088703          1  
4   0.120636          1  

Correlation Matrix:
           feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
feature_1   1.000000  -0.034033  -0.037654  -0.211882   0.120075   0.069321   
feature_2  -0.034033   1.000000  -0.146354  -0.011783  -0.082393  -0.228878   
feature_3  -0.037654  -0.146354   1.000000  -0.214816  -0.034695  -0.021957   
feature_4  -0.211882  -0.011783  -0.214816   1.000000   0.187530  -0.

In [4]:
corr = correlation_matrix.abs()
corr

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,dependent
feature_1,1.000000,0.034033,0.037654,0.211882,0.120075,0.069321,0.047966,0.086023
feature_2,0.034033,1.000000,0.146354,0.011783,0.082393,0.228878,0.115660,0.163234
feature_3,0.037654,0.146354,1.000000,0.214816,0.034695,0.021957,0.081690,0.161925
feature_4,0.211882,0.011783,0.214816,1.000000,0.187530,0.218485,0.016005,0.004140
feature_5,0.120075,0.082393,0.034695,0.187530,1.000000,0.133339,0.249953,0.050942
feature_6,0.069321,0.228878,0.021957,0.218485,0.133339,1.000000,0.026299,0.117320
feature_7,0.047966,0.115660,0.081690,0.016005,0.249953,0.026299,1.000000,0.007861
dependent,0.086023,0.163234,0.161925,0.004140,0.050942,0.117320,0.007861,1.000000


In [18]:
drops = []
print(np.triu(corr.values, 1))
ix, cn = np.where(np.triu(corr.values, 1) > 0.2)


[[0.         0.0340325  0.03765408 0.21188195 0.12007498 0.06932149
  0.04796636 0.08602277]
 [0.         0.         0.14635362 0.01178258 0.08239331 0.22887782
  0.11566033 0.16323446]
 [0.         0.         0.         0.21481643 0.03469451 0.02195684
  0.08168975 0.1619246 ]
 [0.         0.         0.         0.         0.18752985 0.21848486
  0.01600502 0.0041396 ]
 [0.         0.         0.         0.         0.         0.13333937
  0.24995276 0.0509425 ]
 [0.         0.         0.         0.         0.         0.
  0.02629906 0.11731969]
 [0.         0.         0.         0.         0.         0.
  0.         0.00786078]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]]


In [23]:
print(ix)
print(cn)



[0 1 2 3 4]
[3 5 3 5 6]


In [28]:
import numpy as np

# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Define a threshold
threshold = 5

# Use np.where to replace elements greater than the threshold with -1
ix= np.where(array_2d > threshold)

print("Original Array:")
print(array_2d)
print("\nResulting Array:")
print(ix)


Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Resulting Array:
(array([1, 2, 2, 2]), array([2, 0, 1, 2]))


In [32]:
x = np.arange(10)
x.shape = (2, 5)
print(x)
x[1, 3]


[[0 1 2 3 4]
 [5 6 7 8 9]]


8

In [40]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x[0, 1]

2